back to vm

diff --git a/main b/main
--- a/main
+++ b/main
@@ -3,15 +3,34 @@
 #PBS -l nodes=1:ppn=8
 #PBS -l walltime=00:20:00
 
-module load singularity
+#module load singularity
 
+rm -f finished
 rm -r images
 rm -r images.json
 
-singularity run -e /N/u/brlife/Carbonate/plot3dsurfaces-2017-11-15-4a6c5a3759e0.img
+#singularity run -e /N/u/brlife/Carbonate/plot3dsurfaces-2017-11-15-4a6c5a3759e0.img
 
-if [ ! -s images.json ];
+source activate dipyenv
+
+export PYTHONPATH=/usr/local/nibabel:$PYTHONPATH
+export PYTHONPATH=/usr/local/dipy:$PYTHONPATH
+export PYTHONPATH=/usr/local/xvfbwrapper:$PYTHONPATH
+
+
+echo "starting main"
+
+NUMFILES=`python main.py` 
+
+
+#check for output files
+count=$(ls images/*.png | wc -l)
+if [ $count == $NUMFILES ];
 then 
-	echo "images.json missing"
-	exit 1
+  echo 0 > finished
+else
+  echo "images missing"
+  echo 1 > finished
+  exit 1
 fi
+
